#!/bin/bash
yum update -y
yum install -y httpd
yum install -y wget
chkconfig httpd on
cd /var/www/html
wget https://github.com/jaganaath/aws_tutorial/raw/master/compute/index.html
service httpd start
